#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use Symfony\Component\Console\Application;

$console = new Application();
$console->add(new \ApiGeneratorOrg\TestCommand());
$console->run();
